### PR TITLE
Fix observer list losing filtering

### LINKED ISSUE #472: [NGO Admin] [Monitoring observers]  Filter reset on back button in monitoring observers list
When an user applies multiple filters to the observer list (ex. by tags) and then views the details of an observer, clicking the back button resets the list, eliminating all applied filters. The expected behaviour is for the applied filters to persist until the user navigates to a different section.

Steps to Reproduce:

1. Navigate to the monitoring observers list.
2. Apply multiple filters to the list (apply some tags)
3. Click on an observer to view his details.
4. Click the back button to return to the observer list.

Actual Result:
The observer list resets, removing all applied filters.

Expected Result:
The observer list should retain the applied filters until the user navigates to a different section.

### PR DESCRIPTION
**Pull request by imdeaconu**
### Changes
- Fixes #472 
- Adds a proposal for a new, unified filtering system

### The proposed filtering system
The proposed filtering system uses reusable components that encapsulate their business logic so their behavior should be identical throughout the app. The system uses query params as a single source of truth so the state is saved through navigation and can be bookmarked or shared via an URL.

### CODE REVIEW

File: web/src/features/filtering/components/ActiveFilters.tsx [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+  isArray?: boolean;
+}
+
+type SearchParams = {
+  [key: string]: any;
+};
+
+const HIDDEN_FILTERS = ['pageSize', 'pageNumber'];
+const FILTER_LABELS = new Map<string, string>([
+  ['status', 'Observer status'],
```
Comment (idormenco) [inline web/src/features/filtering/components/ActiveFilters.tsx:17]: - we should extract this keys in a enum/class so we can not rely on magic strings
- use the key from enum/class in `~/features/filtering/components/ObserverStatusSelect.tsx` line 26
- key name should be `monitoringObserverStatus` since we have status on many entities

File: web/src/features/filtering/components/ObserverStatusSelect.tsx [hunk 2]
```diff
@@ -0,0 +1,37 @@
+import { FC } from 'react';
+import { useFilteringContainer } from '../hooks/useFilteringContainer';
+import { GenericSelectFilter, GenericSelectFilterOption } from './GenericSelectFilter';
+
+const observerStatusOptions: GenericSelectFilterOption[] = [
```
Comment (idormenco) [inline web/src/features/filtering/components/ObserverStatusSelect.tsx:5]: name should be `monitoringObserverStausOptions` since this filer will be used by ngo admins 
rename component file as well

File: web/src/features/filtering/components/ObserverStatusSelect.tsx [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+  {
+    value: 'Active',
+    label: 'Active',
+  },
+
+  {
+    value: 'Pending',
```
Comment (idormenco) [inline web/src/features/filtering/components/ObserverStatusSelect.tsx:12]: please use `MonitoringObserverStatus` from `~/src/features/monitoring-observers/models/monitoring-observer.ts`
if needed you can move the types in a better suited place

File: web/src/features/filtering/components/ObserverStatusSelect.tsx [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+    label: 'Pending',
+  },
+
+  {
+    value: 'Suspended',
+    label: 'Suspended',
+  },
+];
+
+export const ObserverStatusSelect: FC = () => {
```
Comment (idormenco) [inline web/src/features/filtering/components/ObserverStatusSelect.tsx:22]: rename to `MonitoringObserverStatusSelect`

File: web/src/features/filtering/components/ObserverTagsSelect.tsx [hunk 5]
```diff
@@ -0,0 +1,45 @@
...
+  DropdownMenuCheckboxItem,
+  DropdownMenuContent,
+  DropdownMenuTrigger,
+} from '@/components/ui/dropdown-menu';
+import { useCurrentElectionRoundStore } from '@/context/election-round.store';
+import { useMonitoringObserversTags } from '@/hooks/tags-queries';
+import { FC } from 'react';
+import { useFilteringContainer } from '../hooks/useFilteringContainer';
+
+export const ObserverTagsSelect: FC = () => {
```
Comment (idormenco) [inline web/src/features/filtering/components/ObserverTagsSelect.tsx:12]: rename to `MonitoringObserverTagsSelect`

**Review by idormenco — CHANGES_REQUESTED** [review]

File: web/src/features/filtering/components/ObserverStatusSelect.tsx
Comment (idormenco) [inline web/src/features/filtering/components/ObserverStatusSelect.tsx:1]: since this filter is used only in `features/monitoring-observers` maybe it should live under `/features/monitoring-observers/filtering` ?

**Review by idormenco — CHANGES_REQUESTED** [review]

File: web/src/features/filtering/components/GenericSelectFilter.tsx [hunk 6]
```diff
@@ -0,0 +1,39 @@
...
+};
+
+interface GenericSelectFilterProps {
+  placeholder: string;
+  value: string;
+  options: GenericSelectFilterOption[];
+  onChange: (value: string) => void;
+}
+
+export const GenericSelectFilter: FC<GenericSelectFilterProps> = (props) => {
```
Comment (idormenco) [inline web/src/features/filtering/components/GenericSelectFilter.tsx:16]: please rename to SelectFilter.

**Review by idormenco — CHANGES_REQUESTED** [review]

**Review by idormenco — APPROVED** [review]

**Comment by idormenco** [comment]
LGTM
