### PR TITLE
[NGO Admin] Rewrite the tag selector component 

### LINKED ISSUE #655: [NGO Admin] The tag input doesn't reset after a new tag is created and added to an observer
Description:
The tag input doesn't reset after a new tag is  created and added to an observer. 

Steps to Reproduce:

1. Edit an observer.
2. Try adding a tag that doesn't exist yet.

Expected behavior:
The input should reset so the user can create a new tag.

### PR DESCRIPTION
**Pull request by imdeaconu**
Fixes #655. The new component uses the headless-ui combobox as a base.

### CODE REVIEW

File: web/src/components/ui/tag-selector.tsx [hunk 1]
```diff
@@ -36,192 +16,120 @@ interface TagsSelectFormFieldProps
...
+                    <Separator orientation='vertical' className='flex min-h-6 h-full' />
+                  </>
+                )}
+                <Popover.Button>
+                  <ChevronDown className='h-4 mx-2 cursor-pointer text-muted-foreground' />
+                </Popover.Button>
+              </div>
+            </Popover.Button>
+
+            <Popover.Panel className='w-[240px] flex flex-col gap-4 z-50 w-72  rounded-md border bg-popover p-4 text-popover-foreground shadow-md outline-none data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2 p-0 drop-shadow-sm absolute z-10  '>
```
Comment (idormenco) [inline web/src/components/ui/tag-selector.tsx:100]: cleanup classes since it has multiple `z-*`, `p-*` also `w-[240px]` and `w-72` are the same

**Review by idormenco — CHANGES_REQUESTED** [review]

**Review by idormenco — APPROVED** [review]
